services:
  urlshortener.api:
    image: ${DOCKER_REGISTRY-}urlshortenerapi
    build:
      context: .
      dockerfile: URLShortener.API/Dockerfile
    depends_on:
      - cache
      - db
    ports:
      - 8080:8080
      - 8081:8081
    networks:
      - shortener-network

  urlshortener.front:
    image: urlshortenerfront
    build:
      context: .
      dockerfile: ./urlshortener/Dockerfile
    depends_on:
      - cache
      - db
      - urlshortener.api 
    environment:
      NODE_ENV: production
    ports:
      - 3000:80
    networks:
      - shortener-network

  cache:
    image: redis
    command: redis-server --requirepass Redis2024!
    ports:
      - "6379:6379"
    networks:
      - shortener-network

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "Postgres2024!"
      POSTGRES_DB: "UriShortener"
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - shortener-network

networks:
  shortener-network: